export const actionType = {
    TOGGLE_MENU: 'TOGGLE_MENU',
    TOGGLE_SUPERMAN: 'TOGGLE_SUPERMAN',
    SET_NEW_GAME_PARAMETER: 'SET_NEW_GAME_PARAMETER',
    START_GAME: 'START_GAME',
    TOGGLE_FLAG: 'TOGGLE_FLAG',
    OPEN_CELL: 'OPEN_CELL',
    MOVE_VIEWPORT: 'MOVE_VIEWPORT',
    SET_MESSAGE: 'SET_MESSAGE',
    SET_FIELD: 'SET_FIELD',
    UPDATE_FLAG_COUNT: 'UPDATE_FLAG_COUNT',
    SET_VIEWPORT_OFFSET: 'SET_VIEWPORT_OFFSET',
    SET_GAME_STAGE: 'SET_GAME_STAGE',
    SET_VIEWPORT_SIZE: 'SET_VIEWPORT_SIZE'
}

export const gameStage = {
    NOT_STARTED: 'NOT_STARTED',
    STARTED: 'STARTED',
    WON: 'WON',
    LOST: 'LOST'
}