export const actionType = {
    TOGGLE_MENU: 'TOGGLE_MENU',
    TOGGLE_SUPERMAN: 'TOGGLE_SUPERMAN',
    CHANGE_NEW_GAME_PARAMETER: 'CHANGE_NEW_GAME_PARAMETER',
    START_GAME: 'START_GAME',
    TOGGLE_FLAG: 'TOGGLE_FLAG',
    OPEN_CELLS: 'OPEN_CELLS',
    CHANGE_OFFSET: 'CHANGE_OFFSET',
    TOGGLE_MESSAGE: 'TOGGLE_MESSAGE',
    UPDATE_FIELD: 'UPDATE_FIELD',
    UPDATE_FLAG_COUNT: 'UPDATE_FLAG_COUNT',
    UPDATE_OFFSET: 'UPDATE_VIEWPORT_OFFSET',
    CHANGE_GAME_STAGE: 'CHANGE_GAME_STAGE'
}

export const gameStage = {
    NOT_STARTED: 'NOT_STARTED',
    WAITING: 'WAITING',
    IN_PROGRESS: 'IN_PROGRESS',
    WON: 'WON',
    LOST: 'LOST'
}